import { todayIso } from "@/lib/dates";
import type { UserRole } from "@/lib/types";

/**
 * Pure permission functions for the two "who may mutate this?" policies
 * the business-logic feature centralizes.
 *
 * Two rules:
 *   1. `canDispatcherEditRoute` — dispatcher or admin, AND the route's
 *      date is today or later. Past-date routes are read-only.
 *   2. `canDriverCheckInStop` — only the driver assigned to the route may
 *      check in a stop. Admins and dispatchers MUST NOT generate
 *      check-in rows on a driver's behalf; the driver's audit trail is
 *      the driver's alone.
 *
 * No I/O, no imports from `@/interfaces`. Call sites hold whatever data
 * the check needs (role, route.routeDate, session.userId, route.driverId)
 * and delegate to these functions so the decision is testable in one
 * place.
 */

export interface EditRouteContext {
  /** Session role. Only "dispatcher" or "admin" may edit. */
  role: UserRole;
  /** "YYYY-MM-DD" — matches `Route.routeDate`. */
  routeDate: string;
  /**
   * "YYYY-MM-DD" override for testing. Defaults to `todayIso()` (UTC)
   * when omitted. Production callers leave this undefined and accept the
   * default.
   */
  today?: string;
}

/**
 * Returns true when the caller may edit (add/remove/reorder/transition)
 * the given route.
 *
 * Rules:
 *   - Role must be "dispatcher" or "admin". Drivers and anon are denied.
 *   - Route's date must be today or later. The format is "YYYY-MM-DD"
 *     so lexicographic compare matches chronological compare.
 */
export function canDispatcherEditRoute(ctx: EditRouteContext): boolean {
  if (
    ctx.role !== "dispatcher" &&
    ctx.role !== "admin" &&
    ctx.role !== "office"
  ) {
    return false;
  }
  const today = ctx.today ?? todayIso();
  return ctx.routeDate >= today;
}

export interface CheckInContext {
  /** Session role. Only "driver" may check in. */
  role: UserRole;
  /** The session's userId (profileId). */
  profileId: string;
  /** `route.driverId` from the stop's parent route. */
  routeDriverId: string;
}

/**
 * Returns true when the caller may issue a check-in (arrive / picked up)
 * for a stop on the given route.
 *
 * Rules:
 *   - Role must be "driver". Admins and dispatchers are denied — the
 *     check-in row is the driver's own audit trail and must be
 *     generated by them, not on their behalf.
 *   - The session's `profileId` must match `route.driverId`. Other
 *     drivers cannot check in someone else's stops.
 */
export function canDriverCheckInStop(ctx: CheckInContext): boolean {
  if (ctx.role !== "driver") return false;
  return ctx.profileId === ctx.routeDriverId;
}
